title: Class10CS
description: "This project is based on Class 10 Manipuri Board TextBook."
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

# Disable automatic page collections
just_the_docs:
  mermaid: 
    enable: true
    version: "10.6.1"
    theme: "default"
  collections:
    chapters:
      nav_exclude: true  # This prevents auto-listing of chapter pages

  includes:
    head_custom: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
