title: Class10CS
description: "This project is based on Class 10 Manipuri Board TextBook."
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

collections:
  chapters:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
